// 센터 소개/오시는 길: 공통 레이아웃과 site.config.mjs를 재사용합니다.
export function centerPages(config, {esc,icon,btn,link}) {
 const value=(v,empty)=>esc(v?.trim()||empty);
 const nav=(current)=>`<div class="center-navigation"><div class="container center-width"><nav class="center-breadcrumb" aria-label="현재 위치"><ol><li>${link('/','홈')}</li><li>${link('/about','센터 소개')}</li><li aria-current="page">${current==='about'?'센터 소개':'오시는 길'}</li></ol></nav><nav class="center-tabs" aria-label="센터 소개 하위 메뉴">${[['about','센터 소개'],['location','오시는 길']].map(([r,t])=>`<a href="/${r}" ${current===r?'aria-current="page"':''}>${t}</a>`).join('')}</nav></div></div>`;
 const disabled=(label)=>`<button type="button" class="button secondary" disabled>${label}</button>`;
 const phone=()=>config.phone?`<a class="button" href="tel:${esc(config.phone.replace(/[^+\d]/g,''))}">${icon('phone')}전화 상담</a>`:disabled('전화번호 입력 예정');
 const cta=(kind)=>`<section class="center-cta"><div class="container center-width"><span class="eyebrow">함께 준비하는 돌봄</span><h2>${kind==='about'?'어떤 돌봄이 필요할지,<br>함께 이야기해보세요':'방문 전, 먼저 상담해보세요'}</h2>${kind==='about'?'<p>어르신의 상황과 궁금한 점을 남겨주시면<br>이용 가능한 서비스를 안내해드립니다.</p>':'<p>방문 가능 시간과 궁금한 내용을 먼저 확인해 주세요.</p>'}<div class="button-row">${kind==='about'?btn('/contact','상담 신청')+btn('/location','오시는 길',true):phone()+btn('/contact','온라인 상담 신청',true)}</div>${!config.contactEndpoint?'<p class="center-caption">현재 온라인 상담 접수는 준비 중입니다. 상담 페이지에서 안내를 확인해 주세요.</p>':''}</div></section>`;
 const principles=[['person','어르신 존중','생활 습관과 의사를 존중하는 돌봄을 지향합니다.'],['heart','생활에 맞는 도움','필요한 지원이 무엇인지 함께 살핍니다.'],['file','이해하기 쉬운 안내','서비스 내용과 이용 과정을 차근차근 안내합니다.'],['leaf','보호자와의 소통','돌봄에 관한 고민과 요청을 함께 나눕니다.']];
 const services=[['home-care','방문요양','필요한 시간에 가정을 방문해 어르신의 신체활동과 일상생활을 돕습니다.'],['live-in-care','입주요양','가정에 머무르는 형태의 돌봄을 상담합니다. 근무·휴게 조건과 지원 범위는 계약으로 확인합니다.'],['equipment','노인복지용구 대여','어르신의 생활에 필요한 용구의 이용 방법을 안내합니다. 실제 취급 품목과 대여 가능 여부는 확인이 필요합니다.']];
 const about=`<div class="center-page about-page">${nav('about')}<section class="center-intro container center-width"><div class="intro-copy"><p class="eyebrow">강남간호방문요양센터 소개</p><h1>익숙한 집에서 이어지는 일상,<br>정성을 담은 돌봄으로<br class="intro-break"> 함께합니다</h1><p class="intro-description">어르신의 생활과 보호자의 고민을 함께 살피며,<br>방문요양·입주요양·복지용구 이용을 안내합니다.</p></div><figure class="intro-photo"><img src="/assets/hero.webp" width="1600" height="900" fetchpriority="high" alt="한국 가정에서 어르신과 요양보호사가 손을 잡고 대화하는 돌봄 연출 이미지"><figcaption>서비스 이해를 위한 연출 이미지이며 실제 센터 직원 사진이 아닙니다.</figcaption></figure></section><section class="center-greeting container center-width"><div><span class="eyebrow">센터 인사말</span><h2>어르신의 생활을<br>이해하는 것부터 시작합니다</h2></div><div class="greeting-body"><p>부모님께 도움이 필요해졌을 때, 어떤 돌봄을 선택해야 할지, 가족이 곁에 없는 시간은 어떻게 채워야 할지 고민이 생깁니다. 그 마음을 이해하며 어르신의 생활과 보호자의 상황을 먼저 살피고자 합니다.</p><p>오래 이어온 생활 습관과 스스로 선택하는 일상은 어르신에게 소중합니다. 익숙한 집에서 자신의 생활을 이어갈 수 있도록, 의사를 존중하며 필요한 도움을 함께 찾아갑니다.</p><p>방문요양부터 입주요양, 복지용구까지 서비스의 차이와 이용 과정을 이해하기 쉽게 안내하겠습니다. 처음 알아보는 가족도 필요한 내용을 차근차근 확인할 수 있도록 함께하겠습니다.</p><p class="greeting-sign">${esc(config.name)}</p></div></section><section class="center-principles"><div class="container center-width"><span class="eyebrow">돌봄의 원칙</span><h2>돌봄에서 소중하게 생각하는 것</h2><div class="principle-grid">${principles.map(([i,h,p])=>`<article><div class="principle-icon">${icon(i)}</div><h3>${h}</h3><p>${p}</p></article>`).join('')}</div></div></section><section class="center-services container center-width"><div class="center-section-top"><div><span class="eyebrow">제공 서비스</span><h2>일상에 필요한 도움을 연결합니다</h2></div><p>어르신의 상황에 맞는<br>이용 방법을 살펴보세요.</p></div><div class="center-service-list">${services.map(([slug,h,p],n)=>`<article><span class="service-number">0${n+1}</span><h3>${h}</h3><p>${p}</p>${link('/services/'+slug,`${h} 자세히 보기 <span aria-hidden="true">→</span>`,'text-link')}</article>`).join('')}</div></section><section class="center-process container center-width"><span class="eyebrow">서비스 이용 과정</span><h2>처음 이용하셔도 차근차근 안내합니다</h2><ol class="center-step-list">${[['상담','어르신의 상황과 필요한 도움을 나눕니다.'],['이용 조건 확인','이용 자격과 서비스 가능 여부를 살핍니다.'],['서비스 계획 및 계약','지원 범위와 일정, 비용을 함께 확인합니다.'],['서비스 시작','계약한 계획에 따라 돌봄을 시작합니다.']].map(([h,p],i)=>`<li><span class="step-count">0${i+1}</span><div><h3>${h}</h3><p>${p}</p></div></li>`).join('')}</ol>${link('/guide/process','서비스 이용 절차 자세히 보기 →','text-link')}</section>${cta('about')}</div>`;
 const address=config.address?.trim();
 const fullAddress=[address,config.addressDetail?.trim()].filter(Boolean).join(' ');
 function safeMap(raw,host){try{const u=new URL(raw);return u.protocol==='https:'&&(u.hostname===host||u.hostname.endsWith('.'+host))?u.href:null;}catch{return null;}}
 const maps=address?[['네이버지도',safeMap(config.naverMapUrl,'naver.com')||safeMap(config.naverMapUrl,'naver.me')||`https://map.naver.com/p/search/${encodeURIComponent(address)}`],['카카오맵',safeMap(config.kakaoMapUrl,'kakao.com')||`https://map.kakao.com/link/search/${encodeURIComponent(address)}`]]:[];
 const mapLinks=maps.map(([name,url])=>`<a class="button secondary" href="${esc(url)}" target="_blank" rel="noopener noreferrer">${name} 길찾기 <span class="new-window">새 창 ↗</span></a>`).join('');
 const mapPanel=`<section class="center-map ${address?'map-linked':''}" aria-labelledby="map-heading"><div class="map-symbol">${icon('file')}</div><p class="eyebrow">센터 위치 안내</p><h2 id="map-heading">${address?'지도에서 위치를 확인하세요':'지도 안내 준비 중'}</h2><p>${address?'아래 지도 서비스에서 센터 주소를 확인하고<br>검색 결과의 길찾기를 선택해 주세요.':'센터 주소가 등록되면<br>지도를 확인할 수 있습니다'}</p>${address?`<p class="map-address">${esc(address)}</p><div class="button-row">${mapLinks}</div><p class="center-caption">지도가 열리지 않아도 옆의 주소와 연락 정보를 확인할 수 있습니다.</p>`:'<span class="map-pending-label">주소 확인 중</span>'}</section>`;
 const location=`<div class="center-page location-page">${nav('location')}<section class="location-heading container center-width"><p class="eyebrow">방문 안내</p><h1>오시는 길</h1><p>센터 위치와 방문에 필요한 정보를 안내합니다.</p></section><div class="center-location-grid container center-width"><section class="center-location-info" aria-labelledby="center-info-heading"><span class="eyebrow">센터 정보</span><h2 id="center-info-heading">${esc(config.name)}</h2><dl>${[['도로명주소',value(address,'주소 확인 중')],['상세주소',value(config.addressDetail,'상세주소 확인 중')],['대표 전화',config.phone?`<a href="tel:${esc(config.phone.replace(/[^+\d]/g,''))}">${esc(config.phone)}</a>`:'전화번호 입력 예정'],['운영시간',value(config.hours,'운영시간 확인 중')]].map(([k,v])=>`<div><dt>${k}</dt><dd>${v}</dd></div>`).join('')}</dl><div class="location-actions">${address?`<button class="button secondary" type="button" data-copy-address="${esc(fullAddress)}" aria-describedby="copy-status">주소 복사</button>`:disabled('주소 복사 · 준비 중')}${phone()}</div><p id="copy-status" class="copy-status" role="status" aria-live="polite"></p>${!address?`<div class="map-actions-disabled">${disabled('네이버지도 길찾기 · 준비 중')}${disabled('카카오맵 길찾기 · 준비 중')}</div><p class="center-caption">주소 확인 후 복사와 길찾기를 이용할 수 있습니다.</p>`:''}</section>${mapPanel}</div><section class="visit-guidance container center-width"><span class="eyebrow">교통 및 방문 안내</span><h2>방문 전에 확인해 주세요</h2><div class="visit-rows"><article><div class="visit-label">${icon('person')}<h3>대중교통</h3></div><p>${value(config.publicTransport,'교통편 확인 중')}</p></article><article><div class="visit-label">${icon('chair')}<h3>자가용·주차</h3></div><p>${value(config.parking,'주차 정보 확인 중')}</p></article><article><div class="visit-label">${icon('phone')}<h3>방문 전 안내</h3></div><p>상담을 위해 방문하실 경우, 사전에 연락해 방문 가능 시간을 확인해주세요.</p></article></div></section><section class="center-area"><div class="container center-width"><div><span class="eyebrow">서비스 이용 지역</span><h2>센터 위치와<br>돌봄을 받는 곳은 다를 수 있습니다</h2></div><div><p>${value(config.serviceArea,'서비스 이용 가능 여부는 어르신이 계신 지역과 희망 서비스에 따라 상담을 통해 확인해주세요.')}</p><p class="center-caption">센터 방문 위치와 방문요양·입주요양·복지용구의 서비스 가능 지역은 구분하여 안내합니다.</p>${link('/contact','이용 지역 상담 안내 →','text-link')}</div></div></section>${cta('location')}</div>`;
 return {about,location};
}
