import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
import config from './site.config.mjs';import {centerPages} from './center-pages.mjs';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const helper={esc,icon:()=>'',btn:(u,t)=>`<a href="${u}">${t}</a>`,link:(u,t)=>`<a href="${u}">${t}</a>`};
const empty=centerPages(config,helper);assert.match(empty.location,/주소 확인 중/);assert.ok(!empty.location.includes('data-copy-address='));assert.ok(!empty.location.includes('href="https://map'));assert.match(empty.about,/aria-current="page">센터 소개/);assert.match(empty.location,/aria-current="page">오시는 길/);
const filled=centerPages({...config,address:'테스트용 도로명주소 '.repeat(9),addressDetail:'테스트 상세주소 101호',phone:'010-0000-0000',name:'테스트용 긴 센터 이름 '.repeat(5),naverMapUrl:'javascript:alert(1)',kakaoMapUrl:'https://evil.example.com'},helper);
assert.match(filled.location,/data-copy-address=/);assert.match(filled.location,/map\.naver\.com\/p\/search\//);assert.match(filled.location,/map\.kakao\.com\/link\/search\//);assert.match(filled.location,/target="_blank" rel="noopener noreferrer"/);assert.ok(!filled.location.includes('javascript:'));assert.ok(!filled.location.includes('evil.example'));
async function copyCase(clipboard){const button={dataset:{copyAddress:'테스트 주소'},addEventListener(n,f){this.handler=f;}};const status={textContent:''};const stub={addEventListener(){},querySelector(){return stub;}};const doc={querySelector(s){return s==='#contact-form'?null:s==='#copy-status'?status:stub;},querySelectorAll(s){return s==='[data-copy-address]'?[button]:[];},addEventListener(){}};vm.runInNewContext(fs.readFileSync('dist/app.js','utf8'),{document:doc,location:{pathname:'/location/'},navigator:{clipboard}});await button.handler();return status.textContent;}
let copied='';assert.equal(await copyCase({writeText:async s=>{copied=s;}}),'주소를 복사했습니다.');assert.equal(copied,'테스트 주소');assert.match(await copyCase({writeText:async()=>{throw new Error('denied')}}),/복사하지 못/);assert.match(await copyCase(undefined),/직접 복사/);
if(process.argv.includes('--fixture')){fs.mkdirSync('dist/__qa',{recursive:true});const template=fs.readFileSync('dist/location/index.html','utf8');fs.writeFileSync('dist/__qa/long-location.html',template.replace(/<main id="main">[\s\S]*?<\/main>/,`<main id="main"><p>검증용 가상 데이터 · 실제 센터 정보 아님</p>${filled.location}</main>`));}
console.log('PASS: empty/configured location, long data, safe map links, active subnavigation, clipboard success/denied/unavailable.');
